export const COURSE_ACTION_TYPES={
    SET_COURSE_DATA:'SET_COURSE_DATA',
    GET_COURSES_DATA: 'GET_COURSES_DATA',
    COURSES_ERROR: 'COURSES_ERROR'
}

// export const GET_COURSES = 'GET_COURSES';
// export const COURSES_ERROR = 'COURSES_ERROR';